name: Updater

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update-releases:
    name: Sync with upstream
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: upstream
          fetch-depth: 1

      - name: Update
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.REPOSITORY }}/releases > releases.json

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add releases.json
          git commit -m "Update releases.json"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git upstream
